#!/bin/bash
source /opt/local/strips/ITk/sht31-to-influx/sht-venv/bin/activate

JSON_FILE="/opt/local/strips/ITk/sht31-to-influx/docs/sensor-info.json"
PYTHON_SCRIPT="/opt/local/strips/ITk/sht31-to-influx/single-sensor-connect.py"

# Function to run a single sensor instance
run_sensor() {
  local device_name="$1"
  local address="$2"

  python3 "$PYTHON_SCRIPT" --device_name "$device_name" --address "$address" 
}

# Loop through devices in the JSON config
jq -c '.[]' "$JSON_FILE" | while read -r row; do
  device_name=$(echo "$row" | jq -r '.device_name')
  address=$(echo "$row" | jq -r '.address')

  run_sensor "$device_name" "$address" &
done

wait
