#!/bin/bash
source /opt/local/strips/ITk/sht31-to-influx/sht-venv/bin/activate

JSON_FILE="/opt/local/strips/ITk/sht31-to-influx/docs/sensor-info.json"
PYTHON_SCRIPT="/opt/local/strips/ITk/sht31-to-influx/scanner.py"

# Function to run a single sensor instance
run_sensor() {
  local address="$1"
    python3 "$PYTHON_SCRIPT" --address "$address"
}

# Loop through devices in the JSON config
jq -c '.[]' "$JSON_FILE" | while read -r row; do
  address=$(echo "$row" | jq -r '.address')

  run_sensor "$address" &
done

wait
