#!/bin/bash
source /opt/local/strips/ITk/sht31-to-influx/sht-venv/bin/activate

db=$1
usr=$2
pwrd=$3

JSON_FILE="/opt/local/strips/ITk/sht31-to-influx/docs/sensor-info.json"
PYTHON_SCRIPT="/opt/local/strips/ITk/sht31-to-influx/single-sensor-connect.py"

# Function to run a single sensor instance
run_sensor() {
  local db="$1"
  local usr="$2"
  local pwrd="$3"
  local device_name="$4"
  local address="$5"

  # Check for connection, establish if none
  if ! bluetoothctl info "$address" | grep -q "Connected: yes"; then
    bluetoothctl connect "$address"
    bluetoothctl trust "$address"
    python3 "$PYTHON_SCRIPT" --device_name "$device_name" --address "$address"
  fi

  python3 "$PYTHON_SCRIPT" --device_name "$device_name" --address "$address" | python3 moneater.py eaters.temphumeater.TempHumEater --host 128.3.50.38 --port 8086 --database "$db" --user "$usr" --password "$pwrd" --table TempHum 
}

# Loop through devices in the JSON config
jq -c '.[]' "$JSON_FILE" | while read -r row; do
  device_name=$(echo "$row" | jq -r '.device_name')
  address=$(echo "$row" | jq -r '.address')

  run_sensor "$db" "$usr" "$pwrd" "$device_name" "$address" &
done

wait
